### ISSUE TITLE
MVP to-do list

### ISSUE THREAD

**Issue by txshub** [txshub/not-geoguessr#1]
### Reduce re-render count
-  [x] Move dialog related state parameters and open/close functionality inside the dialog component.
- [x] Move drawer related state parameters and open/close functionality into a separate component.

### Possible source for bugs in the future
- [ ] Have a googleMapsApi object passed around after the LoadScript component has loaded instead of going for `window.google.maps`.
- [x] Consider changing functional components to class components.
  - _Started this, will do it where it is appropriate_

### Location selection on map
- [x] Add one marker when clicking on the map (move it if it already exists).
- [x] Add a button to confirm the selection on the map.
- [x] Button to be placed below the map, disabled if no marker on the map.

### Round result
- [x] Initialise the street view location outside of `StreetView`.
- [x] Popup that displays the distance between the selected and actual original location when map location is selected.
- [x] Have a button on the popup for restarting from a new location.
- [x] Display the map with the 2 locations and a line linking them.

### Initial location
- [x] Have a button for resetting the street view to the initial location.
- [x] Try using `StreetViewService.getPanorama()` with random locations to see if they are valid - select the first valid one.

### Restyle
- [x] Try using theme objects with material-ui components and create a standard set of colours.

### Score popup
- ~Have the colours used for the popup reflect the score (short to long distance to be mapped to either warm to cold colours, or traffic light colours)~

### Responsiveness
- [x] Disable map hover functionality and add a button to expand/shrink it on mobile.
- [x] Replace the map and selection button with a floating action button on small screens.
- [x] The Fab will open a full width square map and a selection button below.
- [x] Have items in the drawer appear in a vertical list on small screens.
- [x] Make the result dialog responsive.
